services:
  - type: web
    name: trinity-hostel-management
    env: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn hostel_management.wsgi:application --bind 0.0.0.0:$PORT
    
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-app-name.onrender.com"
